spring.application.name=firstProject
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8081

#FOR DISABLING AUTO BEAN INJECTION OF THE BUILDER OF THE CHATMODEL
spring.ai.chat.client.enabled=false

#set openAI key here
spring.ai.openai.api-key=${OPEN_API_KEY}
